/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardLayoutRouteImport } from './routes/(dashboard)/layout'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authNotAuthorizedRouteImport } from './routes/(auth)/not-authorized'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardLayoutDashboardRouteImport } from './routes/(dashboard)/layout.dashboard'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authNotAuthorizedRoute = authNotAuthorizedRouteImport.update({
  id: '/(auth)/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutDashboardRoute =
  dashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/not-authorized': typeof authNotAuthorizedRoute
  '/register': typeof authRegisterRoute
  '/layout': typeof dashboardLayoutRouteWithChildren
  '/layout/dashboard': typeof dashboardLayoutDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/not-authorized': typeof authNotAuthorizedRoute
  '/register': typeof authRegisterRoute
  '/layout': typeof dashboardLayoutRouteWithChildren
  '/layout/dashboard': typeof dashboardLayoutDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/not-authorized': typeof authNotAuthorizedRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(dashboard)/layout': typeof dashboardLayoutRouteWithChildren
  '/(dashboard)/layout/dashboard': typeof dashboardLayoutDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/not-authorized'
    | '/register'
    | '/layout'
    | '/layout/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/not-authorized'
    | '/register'
    | '/layout'
    | '/layout/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/not-authorized'
    | '/(auth)/register'
    | '/(dashboard)/layout'
    | '/(dashboard)/layout/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authNotAuthorizedRoute: typeof authNotAuthorizedRoute
  authRegisterRoute: typeof authRegisterRoute
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/layout': {
      id: '/(dashboard)/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/not-authorized': {
      id: '/(auth)/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof authNotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/layout/dashboard': {
      id: '/(dashboard)/layout/dashboard'
      path: '/dashboard'
      fullPath: '/layout/dashboard'
      preLoaderRoute: typeof dashboardLayoutDashboardRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
  }
}

interface dashboardLayoutRouteChildren {
  dashboardLayoutDashboardRoute: typeof dashboardLayoutDashboardRoute
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardLayoutDashboardRoute: dashboardLayoutDashboardRoute,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authNotAuthorizedRoute: authNotAuthorizedRoute,
  authRegisterRoute: authRegisterRoute,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
